branches:
  only:
    - master
language: node_js
cache:
  directories:
    - node_modules
after_success:
  - npm run codeclimate
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./deploy.sh || false'
node_js:
  - stable
env:
  global:
    - GH_REF: github.com/ryepup/c4-lab.git
    - secure: bhGx3jV02R6FCI471O6MppnCDC2UqkqcG13pZHHeicctbcRk3wShrnSJRJ0xn6JuR1HIaT92BKwg+xsTItIQ/ge2Q6+3sbQfZYKbEPv8Y0KcvApjkvoZfntU8dUnPMGIrlbTVIRYPxKDA7JHaREr2siNzBWkwu98HnCoUpgfywfraPtU8eEkcGQqy+FgCbM+y6xa4Ha6GUcE5Ml8HcwzLM4lp0yMiBslrKVhY0zC8TpNnJTU3eHl9gRM6x3uAES+mKbJfDaR1UjxY+quViTWLmE+tOMUTRFXZ2KXvDP5Igm5WZWAiwrCwYRyMLHZAlMyECCTVxlrypxniWR3or4lK4eL8XctLwpEuQE0Z8DkW5kRYwhLDf5tYhyhh8EX9VW1p/RMurXg0kSqJO5zMz6I4SA1BJA0fL5y0iNf44Gns6aG9JgMchstHISbGVL/bM0kcM/mqFyVLbZ0cNV1zdEI5jljc+Ln9Ga1ripEf4LRcUSRU/w14GLFq3MRr16lcA7whQDmGbw3kbCWeihpxRhPKhFRlAH5/9vjjcXBmDr9Lon2uZXdK4/gqX4PsYJqZiFrhp4f68fluzkd7GOjMWr9Ud8Uzwnjc6qErb/ZPF2OnszjZasHMuMptYMqt++jJH4IKHJ6z9SuZy+1wHSIyraiBbZJfaMQAutr1m4bfV6ksyo=
